


filename = Angstrem-Inkscape.svg

.PHONY: png
png:
	inkscape --file=$(filename) --export-png=Angstrem.png --without-gui

.PHONY: simplify
simplify:
	inkscape --file=$(filename) --export-plain-svg=Angstrem.svg --without-gui


